# Data Configuration
data_path: "artifacts/TelcoCustomerChurn.csv"
preprocessing_path: "models/preprocessing"

# MLflow Configuration
mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: "telco_churn_experiment"
  artifact_path: "model"

# Model Parameters
model_params:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    random_state: 42
  
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 42
  
  decision_tree:
    max_depth: 5
    min_samples_split: 2
    random_state: 42

# Preprocessing Configuration
categorical_features:
  - "gender"
  - "Partner"
  - "Dependents"
  - "PhoneService"
  - "MultipleLines"
  - "InternetService"
  - "OnlineSecurity"
  - "OnlineBackup"
  - "DeviceProtection"
  - "TechSupport"
  - "StreamingTV"
  - "StreamingMovies"
  - "Contract"
  - "PaperlessBilling"
  - "PaymentMethod"

numerical_features:
  - "tenure"
  - "MonthlyCharges"
  - "TotalCharges"

# API Configuration
api:
  title: "Telco Customer Churn Prediction API"
  description: "API for predicting customer churn"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8000